### ISSUE TITLE
TODO: 使用BS数据库版接口

### ISSUE THREAD

**Issue by Xzavier0722** [ybw0014/ExoticGarden-CN#24]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/ExoticGarden/issues)，且没有找到相同的问题

### 问题描述

粘液科技中文版在最新版本修改了BS的接口，需要插件兼容。BS接口导致的报错等问题请不要再新开issue，如比较紧急影响使用的情况下可在本issue下提交评论。

### 复现步骤

-

### 预期行为

-

### 服务端软件

其他 (请在问题描述里写明)

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

-

### 插件版本

-
